"""Board geometry: flat tilings and 3D surfaces.

This package was split out of a single module; it re-exports the
full public surface. See AGENTS.md for how to add tilings/surfaces.
"""

from __future__ import annotations

from minesweeper.boards.core import (  # noqa: F401
    Board,
    Board3D,
    Cell,
    DIFFICULTIES,
    LatticePoint,
    ROOT3,
    Vec3,
    _HEX_VERTEX_OFFSETS,
    _build,
    _cross,
    _dot,
    _finalize_flat,
    _normalize,
    _orient_outward,
    _shared_vertex_adjacency,
    _tangent_order,
    boundary_components,
    corner_fans,
    euler_characteristic,
    newell_normal,
)
from minesweeper.boards.catalog import (  # noqa: F401
    GROUPS,
    MODES_3D,
    MODE_LABELS,
    SURFACES,
    SURFACE_LABELS,
    SURFACE_SPECS,
    SurfaceSpec,
    TILINGS,
    TILINGS_BY_KEY,
    TILING_SPECS,
    TilingSpec,
    mode_for,
    view_hint,
)
from minesweeper.boards.tilings import (  # noqa: F401
    ARCH_TILINGS,
    ArchTiling,
    _ARCH_CONFIGS,
    _ARCH_TEMPLATES,
    _ArchTemplate,
    _arch_template,
    _elongated_template,
    _hex_lattice_polygons,
    _kagome_template,
    _regular_polygon,
    _rhombitrihex_template,
    _snubhex_template,
    _snubsquare_template,
    _square_on_edge,
    _template,
    _triangle_vertices,
    _trunchex_template,
    _truncsquare_template,
    _trunctrihex_template,
    archimedean_board,
    hex_board,
    hexhex_board,
    square_board,
    triangle_board,
    triangle_grid_board,
)
from minesweeper.boards.aperiodic import (  # noqa: F401
    ZPoint,
    _AFF_IDENT,
    _HAT_OUTLINE,
    _HAT_RULES,
    _HR3,
    _HatTile,
    _MetaTile,
    _ZETA_BASIS,
    _aff_inv,
    _aff_mul,
    _aff_pt,
    _construct_metatiles,
    _construct_patch,
    _hat_base_tiles,
    _hat_leaves,
    _hat_snap,
    _hexpt,
    _line_intersect,
    _match_seg,
    _match_two,
    _rot_about,
    _trot,
    _ttrans,
    _z_add,
    _z_div_phi,
    _z_sub,
    _z_to_xy,
    _zeta_mul,
    hat_board,
    penrose_board,
)
from minesweeper.boards.solids import (  # noqa: F401
    _convex_board3d,
    _geodesic,
    _goldberg_board,
    _gyro_pentagons,
    _icosahedron,
    _polycube_board3d,
    _polycube_surface,
    _tetrahedron,
    c180_board,
    c80_board,
    cube_board,
    cube_frame_board,
    snub_dodecahedron_board,
    sphere_board,
    sphere_triangle_board,
    stepped_bipyramid_board,
    tetrahedron_board,
    tetrahedron_frame_board,
)
from minesweeper.boards.surfaces import (  # noqa: F401
    _arch_cells,
    _assemble,
    _cylinder_point,
    _mobius_point,
    _torus_point,
    arch_cylinder_board,
    arch_mobius_board,
    arch_torus_board,
    cylinder_board,
    cylinder_hex_board,
    cylinder_triangle_board,
    mobius_board,
    mobius_hex_board,
    mobius_triangle_board,
    torus_board,
    torus_hex_board,
    torus_triangle_board,
)
from minesweeper.boards.presets import (  # noqa: F401
    _PRESETS,
    build_board,
)
