"""Export the board conformance oracle (data/conformance.json).

For every ported mode × difficulty, record the board statistics the Python
implementation produces — cell count, mine count, Euler characteristic,
boundary components, edge count, whether the board carries a cell cycle. The
TypeScript vitest suite asserts its own boards reproduce these exactly, so the
two implementations cannot drift. Committed; a CI job regenerates and diffs it.

The ported set grows per milestone: it is exactly the modes present in
data/presets.json (the ones both front-ends build).

Usage: PYTHONPATH=. python scripts/export_conformance.py
"""

from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path

from minesweeper.boards._data import load
from minesweeper.boards.core import (
    DIFFICULTIES,
    boundary_components,
    corner_fans,
    euler_characteristic,
)
from minesweeper.boards.presets import build_board

DATA = Path(__file__).resolve().parent.parent / "data"


def _edge_count(board) -> int:
    edges = set()
    for polygon in board.polygons.values():
        pts = [tuple(round(c, 6) for c in p) for p in polygon]
        for a, b in zip(pts, pts[1:] + pts[:1]):
            edges.add(frozenset((a, b)))
    return len(edges)


def _stats(board) -> dict:
    return {
        "cellCount": len(board.polygons),
        "mineCount": board.mine_count,
        "euler": euler_characteristic(board),
        "boundaryComponents": boundary_components(board),
        "edgeCount": _edge_count(board),
        "vertexCount": len(corner_fans(board)),
        "hasCellCycle": getattr(board, "cell_cycle", None) is not None,
    }


def main() -> int:
    ported = list(load("presets")["presets"].keys())
    out: dict[str, dict[str, dict]] = defaultdict(dict)
    for mode in ported:
        for difficulty in DIFFICULTIES:
            out[mode][difficulty] = _stats(build_board(mode, difficulty))

    payload = {
        "_comment": "Generated by scripts/export_conformance.py. Board "
        "statistics per ported mode × difficulty; the TypeScript conformance "
        "tests assert against these so the two implementations cannot drift.",
        "modes": dict(out),
    }
    path = DATA / "conformance.json"
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"wrote {path} ({len(ported)} modes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
