"""Generate the shared JSON config both front-ends read (`data/*.json`).

The pygame (Python) and Three.js (TypeScript) apps read the same geometry
configuration so it cannot drift and is never written twice. This script is the
single generator:

  * ``data/catalog.json`` — surface specs, the regular tiling specs,
    difficulties, and the menu taxonomy/labels (the pure-data leaves of
    ``catalog.py``; the derivations stay in code in both languages).
  * ``data/presets.json`` — the difficulty presets for the ported modes, as
    ``{mode: {builder, args: {difficulty: [...]}}}``. Only modes that both
    front-ends build live here; more move over as later milestones port them
    (the rest stay in ``presets.py`` until then). Python floats and JS numbers
    are both IEEE-754 doubles and JSON round-trips them exactly.

After editing the source tables below, run ``PYTHONPATH=. python
scripts/export_data.py`` and commit the regenerated JSON. ``catalog.py`` /
``presets.py`` then *load* these files, so the JSON is the source of truth;
this script re-emits them in canonical form (a CI job diffs the result).

Usage: PYTHONPATH=. python scripts/export_data.py
"""

from __future__ import annotations

import json
from pathlib import Path

from minesweeper.boards.catalog import (
    APERIODIC_MODES,
    FAMILY_LABELS,
    MANIFOLD_LABELS,
    MANIFOLD_ORDER,
    MENU_ROOT,
    MENU_ROOT_LABELS,
    OTHER_MODES,
    PICKER_REGULAR,
    REGULAR_TILINGS,
    SHAPED_MODES,
    SOLO_LABELS,
    SPHERE_MODES,
    SURFACE_SPECS,
)
from minesweeper.boards.core import DIFFICULTIES

DATA = Path(__file__).resolve().parent.parent / "data"


def _surface_json(s) -> dict:
    return {
        "key": s.key,
        "label": s.label,
        "prefix": s.prefix,
        "is3d": s.is_3d,
        "needsMirror": s.needs_mirror,
        "boundaryComponents": s.boundary_components,
        "tilt": s.tilt,
        "tilings": sorted(s.tilings) if s.tilings is not None else None,
    }


def _tiling_json(t) -> dict:
    return {
        "key": t.key,
        "label": t.label,
        "chiral": t.chiral,
        "modeOverrides": dict(t.mode_overrides),
    }


def build_catalog() -> dict:
    return {
        "_comment": "Generated by scripts/export_data.py from catalog.py — the "
        "shared source both front-ends read. Edit here (or the Python source) "
        "and re-run the exporter; do not hand-edit downstream copies.",
        "difficulties": list(DIFFICULTIES),
        "surfaces": [_surface_json(s) for s in SURFACE_SPECS],
        "regularTilings": [_tiling_json(t) for t in REGULAR_TILINGS],
        "soloLabels": dict(SOLO_LABELS),
        "menu": {
            "root": list(MENU_ROOT),
            "rootLabels": dict(MENU_ROOT_LABELS),
            "manifoldOrder": list(MANIFOLD_ORDER),
            "manifoldLabels": dict(MANIFOLD_LABELS),
            "pickerRegular": list(PICKER_REGULAR),
            "aperiodic": list(APERIODIC_MODES),
            "familyLabels": dict(FAMILY_LABELS),
            "sphereModes": list(SPHERE_MODES),
            "otherModes": list(OTHER_MODES),
            "shapedModes": list(SHAPED_MODES),
        },
    }


# Archimedean/Laves surface -> builder name. The compact ARCH_PRESETS table
# in presets.py is the authoring source; it is expanded into per-mode rows here.
_ARCH_BUILDER_NAMES = {
    "flat": "archimedean_board",
    "torus": "arch_torus_board",
    "cylinder": "arch_cylinder_board",
    "mobius": "arch_mobius_board",
    "klein": "arch_klein_board",
}


def build_presets() -> dict:
    # presets.py loads presets.json, so the regular/solid rows are their own
    # source of truth; the Archimedean/Laves rows are (re)generated from the
    # ARCH_PRESETS table so the two representations cannot drift. This
    # normalises the whole file so the CI data-sync diff stays canonical.
    from minesweeper.boards.catalog import mode_for
    from minesweeper.boards.presets import ARCH_PRESETS

    committed = json.loads((DATA / "presets.json").read_text(encoding="utf-8"))
    arch_builders = set(_ARCH_BUILDER_NAMES.values())
    presets = {
        mode: spec
        for mode, spec in committed["presets"].items()
        if spec["builder"] not in arch_builders
    }
    for tiling, surfaces in ARCH_PRESETS.items():
        for surface, by_difficulty in surfaces.items():
            presets[mode_for(tiling, surface)] = {
                "builder": _ARCH_BUILDER_NAMES[surface],
                "args": {
                    difficulty: [tiling, *params]
                    for difficulty, params in by_difficulty.items()
                },
            }
    committed["presets"] = presets
    return committed


def main() -> int:
    DATA.mkdir(parents=True, exist_ok=True)
    for name, payload in (("catalog", build_catalog()), ("presets", build_presets())):
        path = DATA / f"{name}.json"
        text = json.dumps(payload, indent=2, ensure_ascii=False) + "\n"
        path.write_text(text, encoding="utf-8")
        print(f"wrote {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
